name: Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: volta-cli/action@v4
            - name: Install dependencies
              run: npm ci
            - name: Tests
              run: npm run test
