name: Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  components: rustfmt, clippy
            - name: Install dependencies
              run: npm ci
            - name: Tests
              run: npm run test
            - name: Rust format
              run: cargo fmt --all -- --check
            - name: Rust Clippy
              run: cargo clippy -- -D warnings
